services:
  cv-web:
    build: .
    container_name: cv_web_frontend
    restart: unless-stopped
    ports:
      - "4173:80"
    environment:
      - VITE_ADMIN_PASSWORD=admin123
    networks:
      - portfolio-network

networks:
  portfolio-network:
    name: joanmata_network
    external: true
