services:
  cv-web:
    build: .
    container_name: cv_web_frontend
    restart: unless-stopped
    ports:
      - "4173:3000"
    env_file:
      - .env
    volumes:
      - ./src/models/cvData.json:/app/src/models/cvData.json
    networks:
      - portfolio-network

networks:
  portfolio-network:
    name: joanmata_network
    external: true
